### ISSUE TITLE
How to build a mono with typescript

### ISSUE THREAD

**Issue by JennyAdolfMJ** [mrward/typescript-addin#17]
Is there a way to build typescript all together while building mono? So that I don't need to install typescript again after building mono?

**Comment by mrward** [comment]
Not sure I completely understand what you are trying to do. Are we talking about building the TypeScript addin at the same time as MonoDevelop?

**Comment by JennyAdolfMJ** [comment]
Yeah, yeah. That's what I mean.

**Comment by mrward** [comment]
I would look at trying one of the following options:

 1. Use `mdtool setup install typescript.mpack` to install the addin
 2. Copy the typescript addin dlls into a subdirectory inside the MonoDevelop's addin directory.
 2. Add the TypeScript project to MonoDevelop's Main.sln file.

**Comment by JennyAdolfMJ** [comment]
Got it. Thank you very much. :)
